//
// ChangePasswordRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChangePasswordRequest: Codable {

    /** 新しいパスワード */
    public var password: String
    /** 現在のパスワード */
    public var oldPassword: String?
    /** リカバリートークン。パスワード再設定用の確認メールに含まれています。 */
    public var recoveryToken: String?

    public init(password: String, oldPassword: String? = nil, recoveryToken: String? = nil) {
        self.password = password
        self.oldPassword = oldPassword
        self.recoveryToken = recoveryToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case password
        case oldPassword = "old_password"
        case recoveryToken = "recovery_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(password, forKey: .password)
        try container.encodeIfPresent(oldPassword, forKey: .oldPassword)
        try container.encodeIfPresent(recoveryToken, forKey: .recoveryToken)
    }
}

