//
// CreateUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateUserRequest: Codable {

    /** ユーザーの名前 */
    public var name: String
    /** ユーザーの表示名 */
    public var nickname: String?
    /** ユーザーの説明 */
    public var description: String?
    /** ロールのUUID。指定したロールがユーザーに割り当てられます。 */
    public var roleUuids: [String]
    /** ユーザーのメールアドレス */
    public var email: String?

    public init(name: String, nickname: String? = nil, description: String? = nil, roleUuids: [String], email: String? = nil) {
        self.name = name
        self.nickname = nickname
        self.description = description
        self.roleUuids = roleUuids
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case nickname
        case description
        case roleUuids = "role_uuids"
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nickname, forKey: .nickname)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(roleUuids, forKey: .roleUuids)
        try container.encodeIfPresent(email, forKey: .email)
    }
}

