//
// CreateUserAPITokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateUserAPITokenRequest: Codable {

    /** APIトークンの名前 */
    public var name: String
    /** 有効期限 */
    public var expiredAt: Date?

    public init(name: String, expiredAt: Date? = nil) {
        self.name = name
        self.expiredAt = expiredAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case expiredAt = "expired_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(expiredAt, forKey: .expiredAt)
    }
}

