//
// CreateMP4Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateMP4Request: Codable {

    /** 時間範囲を指定してその部分のMP4を作成する場合は `true` にします。 */
    public var trimmed: Bool?
    /** 動画の開始時刻からのオフセット（マイクロ秒）。trimmedがtrueの場合は必須です。 */
    public var startOffset: Int?
    /** 長さ（マイクロ秒）。trimmedがtrueの場合は必須です。 */
    public var duration: Int?

    public init(trimmed: Bool? = nil, startOffset: Int? = nil, duration: Int? = nil) {
        self.trimmed = trimmed
        self.startOffset = startOffset
        self.duration = duration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case trimmed
        case startOffset = "start_offset"
        case duration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(trimmed, forKey: .trimmed)
        try container.encodeIfPresent(startOffset, forKey: .startOffset)
        try container.encodeIfPresent(duration, forKey: .duration)
    }
}

