//
// CreateJobRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateJobRequest: Codable {

    /** 計測のUUID */
    public var measUuid: String
    public var type: JobType

    public init(measUuid: String, type: JobType) {
        self.measUuid = measUuid
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case measUuid = "meas_uuid"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(measUuid, forKey: .measUuid)
        try container.encode(type, forKey: .type)
    }
}

