//
// DataPointDataID.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** データID */
public struct DataPointDataID: Codable {

    /** データタイプ */
    public var dataType: String
    /** データID */
    public var dataId: String

    public init(dataType: String, dataId: String) {
        self.dataType = dataType
        self.dataId = dataId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dataType = "data_type"
        case dataId = "data_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dataType, forKey: .dataType)
        try container.encode(dataId, forKey: .dataId)
    }
}

