//
// DataPointDataError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Data String payload. */
public struct DataPointDataError: Codable {

    /** 固定値 `intdash/measurement/get/data/error` */
    public var i: String
    public var d: DataPointDataErrorData

    public init(i: String, d: DataPointDataErrorData) {
        self.i = i
        self.d = d
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case i
        case d
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(i, forKey: .i)
        try container.encode(d, forKey: .d)
    }
}

