//
// DeniedEndpoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeniedEndpoint: Codable {

    /** リソースパス。グロブを使って指定可能です。 */
    public var path: String
    /** HTTPメソッド。グロブを使って指定可能です。 */
    public var method: String

    public init(path: String, method: String) {
        self.path = path
        self.method = method
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case method
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(path, forKey: .path)
        try container.encode(method, forKey: .method)
    }
}

