//
// EdgeConnectionAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EdgeConnectionAllOf: Codable {

    /** ダウンストリームについての情報 */
    public var downstreams: [EdgeConnectionDownstream]
    /** アップストリームについての情報 */
    public var upstreams: [EdgeConnectionUpstream]

    public init(downstreams: [EdgeConnectionDownstream], upstreams: [EdgeConnectionUpstream]) {
        self.downstreams = downstreams
        self.upstreams = upstreams
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case downstreams
        case upstreams
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(downstreams, forKey: .downstreams)
        try container.encode(upstreams, forKey: .upstreams)
    }
}

