//
// EdgeConnectionListPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EdgeConnectionListPage: Codable {

    /** `true` の場合、現在のページが最初のページです。 */
    public var first: Bool
    /** `true` の場合、現在のページが最後のページです。 */
    public var last: Bool
    /** 次のページのパス。現在のページが最後のページの場合は空文字列です。 */
    public var next: String
    /** 前のページのパス。現在のページが最初のページの場合は空文字列です。 */
    public var previous: String
    /** 取得対象の総件数 */
    public var totalCount: Int

    public init(first: Bool, last: Bool, next: String, previous: String, totalCount: Int) {
        self.first = first
        self.last = last
        self.next = next
        self.previous = previous
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case first
        case last
        case next
        case previous
        case totalCount = "total_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(first, forKey: .first)
        try container.encode(last, forKey: .last)
        try container.encode(next, forKey: .next)
        try container.encode(previous, forKey: .previous)
        try container.encode(totalCount, forKey: .totalCount)
    }
}

