//
// ErrorConverted.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ErrorConverted: Codable {

    public enum ModelError: String, Codable, CaseIterable {
        case convertedError = "converted_error"
        case unexpected = "unexpected"
    }
    /** エラーのタイプ。エラーのタイプが `unexpected` の場合は、直ちに処理が中断されます。 */
    public var error: ModelError?
    /** エラーの説明 */
    public var errorDescription: String?
    /** `error_type` が `converted_error` である場合の追加情報 */
    public var errorExtra: AnyCodable?

    public init(error: ModelError? = nil, errorDescription: String? = nil, errorExtra: AnyCodable? = nil) {
        self.error = error
        self.errorDescription = errorDescription
        self.errorExtra = errorExtra
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case errorDescription = "error_description"
        case errorExtra = "error_extra"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(errorDescription, forKey: .errorDescription)
        try container.encodeIfPresent(errorExtra, forKey: .errorExtra)
    }
}

