//
// ErrorProblem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ErrorProblem: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case aboutBlank = "about:blank"
        case invalidRequest = "invalid_request"
        case conflict = "conflict"
        case forbidden = "forbidden"
        case accountLocked = "account_locked"
    }
    /** エラーのタイプ */
    public var type: ModelType
    /** エラーのタイトル */
    public var title: String
    /** 無効なパラメーターについての情報 */
    public var properties: AnyCodable?

    public init(type: ModelType, title: String, properties: AnyCodable? = nil) {
        self.type = type
        self.title = title
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case title
        case properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(properties, forKey: .properties)
    }
}

