//
// ErrorConvertedAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ErrorConvertedAllOf: Codable {

    /** `error_type` が `converted_error` である場合の追加情報 */
    public var errorExtra: AnyCodable?

    public init(errorExtra: AnyCodable? = nil) {
        self.errorExtra = errorExtra
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errorExtra = "error_extra"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errorExtra, forKey: .errorExtra)
    }
}

