//
// Group.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Group: Codable {

    /** グループのUUID */
    public var uuid: String
    /** 親グループのUUID。nullの場合、親グループは存在しません。 */
    public var parentGroupUuid: String?
    /** グループの名前 */
    public var name: String
    /** 作成日時 */
    public var createdAt: Date
    /** 最終更新日時 */
    public var updatedAt: Date

    public init(uuid: String, parentGroupUuid: String?, name: String, createdAt: Date, updatedAt: Date) {
        self.uuid = uuid
        self.parentGroupUuid = parentGroupUuid
        self.name = name
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case parentGroupUuid = "parent_group_uuid"
        case name
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(parentGroupUuid, forKey: .parentGroupUuid)
        try container.encode(name, forKey: .name)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

