//
// Groups.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Groups: Codable {

    public var items: [Group]
    public var page: AuthPage?

    public init(items: [Group], page: AuthPage? = nil) {
        self.items = items
        self.page = page
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case page
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(page, forKey: .page)
    }
}

