//
// ISCPTicket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ISCPTicket: Codable {

    /** iSCPチケット */
    public var ticket: String
    /** 有効期限 */
    public var expiredAt: Date
    /** 作成日時 */
    public var createdAt: Date

    public init(ticket: String, expiredAt: Date, createdAt: Date) {
        self.ticket = ticket
        self.expiredAt = expiredAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ticket
        case expiredAt = "expired_at"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ticket, forKey: .ticket)
        try container.encode(expiredAt, forKey: .expiredAt)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

