//
// JpegQuality.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** JPEGの品質。デフォルトは &#39;middle&#39; です。 - high - middle - low */
public enum JpegQuality: String, Codable, CaseIterable {
    case high = "high"
    case middle = "middle"
    case low = "low"
}
