//
// MeasurementMarkerDetailPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MeasurementMarkerDetailPoint: Codable {

    /** この計測マーカーの時刻。計測の基準時刻からの経過時間（マイクロ秒）で表します。 */
    public var occurredElapsedTime: Int64?

    public init(occurredElapsedTime: Int64? = nil) {
        self.occurredElapsedTime = occurredElapsedTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case occurredElapsedTime = "occurred_elapsed_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(occurredElapsedTime, forKey: .occurredElapsedTime)
    }
}

