//
// MeasurementUploadPostResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MeasurementUploadPostResponse: Codable {

    /** 計測アップロードのUUID */
    @available(*, deprecated, message: "This property is deprecated.")
    public var measUploadUuid: String
    /** 計測への変換ジョブのUUID */
    public var jobUuid: String?
    /** アップロードされたファイルのファイル名 */
    public var fileName: String

    public init(measUploadUuid: String, jobUuid: String? = nil, fileName: String) {
        self.measUploadUuid = measUploadUuid
        self.jobUuid = jobUuid
        self.fileName = fileName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case measUploadUuid = "meas_upload_uuid"
        case jobUuid = "job_uuid"
        case fileName = "file_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(measUploadUuid, forKey: .measUploadUuid)
        try container.encodeIfPresent(jobUuid, forKey: .jobUuid)
        try container.encode(fileName, forKey: .fileName)
    }
}

