//
// MeasurementSectionGetResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MeasurementSectionGetResponse: Codable {

    /** 計測セクションのシリアルナンバー */
    public var serialNumber: String
    /** `true` の場合、計測セクションは処理済みです。 */
    public var processed: Bool
    /** 計測セクションの作成日時。 `processed` が `false` の場合は、この属性はありません。 */
    public var createdAt: String
    /** 計測セクションの最終更新日時。 `processed` が `false` の場合は、この属性はありません。 */
    public var updatedAt: String

    public init(serialNumber: String, processed: Bool, createdAt: String, updatedAt: String) {
        self.serialNumber = serialNumber
        self.processed = processed
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case serialNumber = "serial_number"
        case processed
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(serialNumber, forKey: .serialNumber)
        try container.encode(processed, forKey: .processed)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

