//
// MeasurementMarker.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MeasurementMarker: Codable {
    case typeMeasurementMarkerPoint(MeasurementMarkerPoint)
    case typeMeasurementMarkerRange(MeasurementMarkerRange)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeMeasurementMarkerPoint(let value):
            try container.encode(value)
        case .typeMeasurementMarkerRange(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(MeasurementMarkerPoint.self) {
            self = .typeMeasurementMarkerPoint(value)
        } else if let value = try? container.decode(MeasurementMarkerRange.self) {
            self = .typeMeasurementMarkerRange(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of MeasurementMarker"))
        }
    }
}

