//
// MeasurementJobStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** ジョブのステータス */
public enum MeasurementJobStatus: String, Codable, CaseIterable {
    case ready = "ready"
    case processing = "processing"
    case succeeded = "succeeded"
    case failed = "failed"
    case cancelled = "cancelled"
}
