//
// MeasurementMarkerDetailRange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MeasurementMarkerDetailRange: Codable {

    /** この計測マーカーの始点。この計測の基準時刻からの経過時間（マイクロ秒）で表示します。 */
    public var startElapsedTime: Int64?
    /** この計測マーカーの始点。この計測の基準時刻からの経過時間（マイクロ秒）で表示します。 */
    public var endElapsedTime: Int64?

    public init(startElapsedTime: Int64? = nil, endElapsedTime: Int64? = nil) {
        self.startElapsedTime = startElapsedTime
        self.endElapsedTime = endElapsedTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startElapsedTime = "start_elapsed_time"
        case endElapsedTime = "end_elapsed_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startElapsedTime, forKey: .startElapsedTime)
        try container.encodeIfPresent(endElapsedTime, forKey: .endElapsedTime)
    }
}

