//
// MeasurementBaseTimeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** 計測の基準時刻タイプ */
public enum MeasurementBaseTimeType: String, Codable, CaseIterable {
    case edgeRtc = "edge_rtc"
    case ntp = "ntp"
    case gps = "gps"
    case apiFirstReceived = "api_first_received"
    case volatile = "volatile"
    case manual = "manual"
    case undefined = "undefined"
}
