//
// MP4s.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MP4s: Codable {

    public var items: [MP4]
    public var page: Page

    public init(items: [MP4], page: Page) {
        self.items = items
        self.page = page
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case page
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(page, forKey: .page)
    }
}

