//
// OAuth2ClientWithSecretAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OAuth2ClientWithSecretAllOf: Codable {

    /** OAuth2クライアントID */
    public var clientId: String?
    /** token_endpoint_auth_methodが `none` 以外だったら required */
    public var clientSecret: String?
    /** 名前 */
    public var name: String?
    /** グラントタイプ */
    public var grantTypes: [String]?
    /** トークンエンドポイントの認証方式 */
    public var tokenEndpointAuthMethod: String?
    /** 認可後のリダイレクト先URI */
    public var redirectUris: [String]?
    /** レスポンスタイプ */
    public var responseTypes: [String]?
    /** スコープ */
    public var scopes: [String]?
    /** オーディエンス */
    public var audiences: [String]?
    /** TLSクライアント認証のサブジェクトDN */
    public var tlsClientAuthSubjectDn: String?

    public init(clientId: String? = nil, clientSecret: String? = nil, name: String? = nil, grantTypes: [String]? = nil, tokenEndpointAuthMethod: String? = nil, redirectUris: [String]? = nil, responseTypes: [String]? = nil, scopes: [String]? = nil, audiences: [String]? = nil, tlsClientAuthSubjectDn: String? = nil) {
        self.clientId = clientId
        self.clientSecret = clientSecret
        self.name = name
        self.grantTypes = grantTypes
        self.tokenEndpointAuthMethod = tokenEndpointAuthMethod
        self.redirectUris = redirectUris
        self.responseTypes = responseTypes
        self.scopes = scopes
        self.audiences = audiences
        self.tlsClientAuthSubjectDn = tlsClientAuthSubjectDn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case clientSecret = "client_secret"
        case name
        case grantTypes = "grant_types"
        case tokenEndpointAuthMethod = "token_endpoint_auth_method"
        case redirectUris = "redirect_uris"
        case responseTypes = "response_types"
        case scopes
        case audiences
        case tlsClientAuthSubjectDn = "tls_client_auth_subject_dn"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(clientSecret, forKey: .clientSecret)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(grantTypes, forKey: .grantTypes)
        try container.encodeIfPresent(tokenEndpointAuthMethod, forKey: .tokenEndpointAuthMethod)
        try container.encodeIfPresent(redirectUris, forKey: .redirectUris)
        try container.encodeIfPresent(responseTypes, forKey: .responseTypes)
        try container.encodeIfPresent(scopes, forKey: .scopes)
        try container.encodeIfPresent(audiences, forKey: .audiences)
        try container.encodeIfPresent(tlsClientAuthSubjectDn, forKey: .tlsClientAuthSubjectDn)
    }
}

