//
// PatchEdgeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchEdgeRequest: Codable {

    /** エッジの名前 */
    public var name: String?
    /** エッジの表示名 */
    public var nickname: String?
    /** エッジの説明 */
    public var description: String?

    public init(name: String? = nil, nickname: String? = nil, description: String? = nil) {
        self.name = name
        self.nickname = nickname
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case nickname
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(nickname, forKey: .nickname)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

