//
// Playlist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Playlist: Codable {

    /** プレイリスト */
    public var playlist: String
    /** EXT-X-ENDLISTタグが付いたプレイリスト */
    public var playlistWithEndlistTag: String

    public init(playlist: String, playlistWithEndlistTag: String) {
        self.playlist = playlist
        self.playlistWithEndlistTag = playlistWithEndlistTag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case playlist
        case playlistWithEndlistTag = "playlist_with_endlist_tag"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(playlist, forKey: .playlist)
        try container.encode(playlistWithEndlistTag, forKey: .playlistWithEndlistTag)
    }
}

