//
// SignalConversionOptionJSON.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignalConversionOptionJSON: Codable {

    public enum ValueType: String, Codable, CaseIterable {
        case str = "str"
        case num = "num"
    }
    /** 抽出したいフィールドのパス */
    public var fieldpath: String
    /** 値のタイプ */
    public var valueType: ValueType

    public init(fieldpath: String, valueType: ValueType) {
        self.fieldpath = fieldpath
        self.valueType = valueType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fieldpath
        case valueType = "value_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fieldpath, forKey: .fieldpath)
        try container.encode(valueType, forKey: .valueType)
    }
}

