//
// SignalConversionOptionCSV.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignalConversionOptionCSV: Codable {

    public enum ValueType: String, Codable, CaseIterable {
        case str = "str"
        case num = "num"
    }
    /** デリミタ */
    public var delimiters: [String]
    /** インデックス（左端を0とする列番号） */
    public var index: Int
    public var valueType: ValueType

    public init(delimiters: [String], index: Int, valueType: ValueType) {
        self.delimiters = delimiters
        self.index = index
        self.valueType = valueType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case delimiters
        case index
        case valueType = "value_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(delimiters, forKey: .delimiters)
        try container.encode(index, forKey: .index)
        try container.encode(valueType, forKey: .valueType)
    }
}

