//
// SignalDisplay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignalDisplay: Codable {

    /** 単位 */
    public var unit: String
    /** 最小値 */
    public var min: Int64
    /** 最大値 */
    public var max: Int64
    /** 表示用のフォーマット */
    public var format: String

    public init(unit: String, min: Int64, max: Int64, format: String) {
        self.unit = unit
        self.min = min
        self.max = max
        self.format = format
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unit
        case min
        case max
        case format
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(unit, forKey: .unit)
        try container.encode(min, forKey: .min)
        try container.encode(max, forKey: .max)
        try container.encode(format, forKey: .format)
    }
}

