//
// SignalConversionOptionNumFloatingPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignalConversionOptionNumFloatingPoint: Codable {

    public enum Endian: String, Codable, CaseIterable {
        case big = "big"
        case little = "little"
    }
    public enum Precision: Int, Codable, CaseIterable {
        case _32 = 32
        case _64 = 64
    }
    /** 開始バイト位置 */
    public var startbyte: Int
    /** エンディアン */
    public var endian: Endian
    public var precision: Precision

    public init(startbyte: Int, endian: Endian, precision: Precision) {
        self.startbyte = startbyte
        self.endian = endian
        self.precision = precision
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startbyte
        case endian
        case precision
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(startbyte, forKey: .startbyte)
        try container.encode(endian, forKey: .endian)
        try container.encode(precision, forKey: .precision)
    }
}

