//
// TrashedMeasurements.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TrashedMeasurements: Codable {

    public var items: [Measurement]?
    /** 取得対象の総件数 */
    public var totalCount: Int?

    public init(items: [Measurement]? = nil, totalCount: Int? = nil) {
        self.items = items
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case totalCount = "total_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
    }
}

