//
// UpdateProjectMemberRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateProjectMemberRequest: Codable {

    /** ユーザーに割り当てるロールのUUID。オーナーのロールUUIDは変更できません。 */
    public var roleUuids: [String]?

    public init(roleUuids: [String]? = nil) {
        self.roleUuids = roleUuids
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roleUuids = "role_uuids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(roleUuids, forKey: .roleUuids)
    }
}

