//
// UpdateEmailVerifiedRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateEmailVerifiedRequest: Codable {

    /** メールアドレス確認用トークン */
    public var verificationToken: String

    public init(verificationToken: String) {
        self.verificationToken = verificationToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verificationToken = "verification_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(verificationToken, forKey: .verificationToken)
    }
}

