//
// VideoStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** ステータス */
public enum VideoStatus: String, Codable, CaseIterable {
    case live = "live"
    case unprocessed = "unprocessed"
    case processing = "processing"
    case succeeded = "succeeded"
    case failed = "failed"
}
